apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane
  namespace: gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane
