apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway-system
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: gateway-system
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: tcp
      port: 9000
      targetPort: tcp
